Repository Kong/kubernetes-telemetry, pull requests merged in 2023-06, with the labels that each got.

#158 chore(tests): refactor TestTLSForwarder - allow multiple connections
  pkg/forwarders/tlsforwarder_test.go
Labels: area/tests

#160 feat: send telemetry robustly - always establish new connection
  pkg/forwarders/tlsforwarder.go
  pkg/forwarders/tlsforwarder_test.go
Labels: area/feature

#162 fix(tests): fix tlsforwarder flakiness
  pkg/forwarders/tlsforwarder_test.go
Labels: area/tests

#163 docs: add README.md badges
  README.md
Labels: documentation
